// Code generated by protoc-gen-gogo.
// source: testdata/test.proto
// DO NOT EDIT!

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	testdata/test.proto

It has these top-level messages:
	Message
*/
package testdata

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	N int32  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func init() {
	proto.RegisterType((*Message)(nil), "testdata.Message")
}
